name: proplaya_communication
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  just_audio: ^0.9.39
  path: ^1.9.0
  path_provider: ^2.1.4
  youtube_explode_dart: ^2.2.1
  proplaya_downloader:
    path: ../proplaya_downloader
  proplaya_storage_management:
    path: ../proplaya_storage_management
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.24.0
